CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    senha VARCHAR2(255) NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO usuarios (nome, email, senha) VALUES ('Eduardo Ramos', 'eduardo.ramos@fiap.com.br', 'senha123');


CREATE TABLE colheitadeiras (
    id_colheitadeira NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    capacidade NUMBER NOT NULL,
    tipo VARCHAR2(50) NOT NULL,
    eficiencia NUMBER CHECK (eficiencia BETWEEN 0 AND 1)
);

INSERT INTO colheitadeiras (nome, capacidade, tipo, eficiencia) VALUES ('Colhedora 1', 100, 'manual', 0.8);
INSERT INTO colheitadeiras (nome, capacidade, tipo, eficiencia) VALUES ('Colhedora 2', 200, 'mecanica', 0.9);
INSERT INTO colheitadeiras (nome, capacidade, tipo, eficiencia) VALUES ('Colhedora 3', 300, 'manual', 0.7);

CREATE TABLE colheitas (
    id_colheita NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_colheitadeira NUMBER REFERENCES colheitadeiras(id_colheitadeira),
    data_colheita DATE NOT NULL,
    area_colhida NUMBER NOT NULL,
    produtividade NUMBER NOT NULL, -- em toneladas por hectare
    umidade_solo NUMBER NOT NULL,
    temperatura NUMBER NOT NULL,
    observacoes VARCHAR2(255),
    nome_cultura VARCHAR2(100)
);

-- Inserir colheita
INSERT INTO colheitas (id_colheitadeira, data_colheita, area_colhida, produtividade, umidade_solo, temperatura, observacoes, nome_cultura) VALUES (1, TO_DATE('2024-10-01', 'YYYY-MM-DD'), 50, 10, 55, 30, 'Colheita realizada com sucesso', 'Soja');
INSERT INTO colheitas (id_colheitadeira, data_colheita, area_colhida, produtividade, umidade_solo, temperatura, observacoes, nome_cultura) VALUES (2, TO_DATE('2024-10-02', 'YYYY-MM-DD'), 100, 15, 60, 32, 'Colheita realizada com sucesso', 'Milho');
INSERT INTO colheitas (id_colheitadeira, data_colheita, area_colhida, produtividade, umidade_solo, temperatura, observacoes, nome_cultura) VALUES (3, TO_DATE('2024-10-03', 'YYYY-MM-DD'), 150, 20, 65, 28, 'Colheita realizada com sucesso', 'Trigo');
INSERT INTO colheitas (id_colheitadeira, data_colheita, area_colhida, produtividade, umidade_solo, temperatura, observacoes, nome_cultura) VALUES (1, TO_DATE('2024-10-04', 'YYYY-MM-DD'), 200, 25, 70, 30, 'Colheita realizada com sucesso', 'Soja');
INSERT INTO colheitas (id_colheitadeira, data_colheita, area_colhida, produtividade, umidade_solo, temperatura, observacoes, nome_cultura) VALUES (2, TO_DATE('2024-10-05', 'YYYY-MM-DD'), 250, 30, 75, 32, 'Colheita realizada com sucesso', 'Milho');
INSERT INTO colheitas (id_colheitadeira, data_colheita, area_colhida, produtividade, umidade_solo, temperatura, observacoes, nome_cultura) VALUES (3, TO_DATE('2024-10-06', 'YYYY-MM-DD'), 300, 35, 80, 28, 'Colheita realizada com sucesso', 'Trigo');
